config/routes.rb
DemoApp::Application.routes.draw do
  get "archivos/subir"
  post "archivos/subir"

  get "archivos/listar"

  post "archivos/borrar"

  get "archivos/guardar"
  post "archivos/guardar"

  get "formularios/post"
  post "formularios/post"

  get "redes_sociales/yo"

   root :to => 'redes_sociales#yo'

match 'auth/:provider/callback', to: 'sessions#create'
match 'auth/failure', to: redirect('/')
match 'signout', to: 'sessions#destroy', as: 'signout'
end

app/models/user.rb
def self.from_omniauth(auth)
  where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
    user.provider = auth.provider
    user.uid = auth.uid
    user.name = auth.info.name
    user.oauth_token = auth.credentials.token
    user.oauth_expires_at = Time.at(auth.credentials.expires_at)
    user.save!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery


 private

def current_user
  @current_user ||= User.find(session[:user_id]) if session[:user_id]
end
helper_method :current_user
end

app/controllers/archivos_controller.rb
class ArchivosController < ApplicationController
  
  Ruta_archivos_comentarios = "public/comentarios/comentarios.txt"
  Ruta_archivos="public/archivos/"

  def subir
   @formato_erroneo = false;
   if request.post?
      #Archivo subido por el usuario.
      archivo = params[:archivo];
      #Nombre original del archivo.
      nombre = archivo.original_filename;
      #Directorio donde se va a guardar.
      directorio = Ruta_archivos;
      #Extensión del archivo.
      extension = nombre.slice(nombre.rindex("."), nombre.length).downcase;
      #Verifica que el archivo tenga una extensión correcta.
      if extension == ".pdf" or extension == ".doc" or extension == ".docx"
         #Ruta del archivo.
         path = File.join(directorio, nombre);
         #Crear en el archivo en el directorio. Guardamos el resultado en una variable, será true si el archivo se ha guardado correctamente.
         resultado = File.open(path, "wb") { |f| f.write(archivo.read) };
         #Verifica si el archivo se subió correctamente.
         if resultado
            subir = "ok";
         else
            subir = "error";
         end
         #Redirige al controlador "archivos", a la acción "lista_archivos" y con la variable de tipo GET "subir_archivos" con el valor "ok" si se subió el archivo y "error" si no se pudo.
         redirect_to :controller => "archivos", :action => "listar", :subir => subir;
      else
         @formato_erroneo = true;
      end
    end
 end


 def listar
   #Guardamos la lista de archivos de la carpeta "archivos".
   @archivos = Dir.entries(Ruta_archivos);
   #Mensaje que mostrará si la página viene desde otra acción.
   @mensaje = "";
   #Verificamos si existe la variable subir_archivo por GET.
   if params[:subir_archivo].present?
      if params[:subir_archivo] == "ok";
         @mensaje = "El archivo ha sido subido exitosamente.";
      else
         @mensaje = "El archivo no ha podido ser subido.";
      end
   end
   #Verificamos si existe la variable eliminar_archivo por GET.
   if params[:eliminar_archivo].present?
      if params[:eliminar_archivo] == "ok";
         @mensaje = "El archivo ha sido eliminado exitosamente";
      else
         @mensaje = "El archivo no ha podido ser eliminado.";
      end
   end
   #Verifica si existe el archivo de los comentarios.
   if File.exist?(Ruta_archivos_comentarios)
      @comentarios = File.read(Ruta_archivos_comentarios);
   else
      @comentarios = "";
   end
 end

def borrar
   #Recuperamos el nombre del archivo.
   archivo_a_borrar = params[:archivo_a_borrar];
   #Guardamos la ruta del archivo a eliminar.
   ruta_al_archivo = Ruta_archivos + archivo_a_borrar;
   #Verificamos que el archivo exista para eliminarlo.
   if File.exist?(ruta_al_archivo)
      #Si el archivo existe se intentará eliminarlo. Dentro de la variable resultado se guardará true si se pudo eliminar y false si no.
      resultado = File.delete(ruta_al_archivo);
   else
      #El archivo no existe así que no se pudo eliminar nada.
      resultado = false;
   end
   #Verifica si el archivo se eliminó correctamente.
   if resultado
      eliminar_archivo = "ok";
   else
      eliminar_archivo = "error";
   end
   redirect_to :controller => "archivos", :action => "listar", :eliminar_archivo => eliminar;
 end

  def guardar
   #Si llega por post intentará guardar los comentarios que ha ingresado el usuario.
   if request.post?
      #Guarda los comentarios en una variable
      comentarios = params[:comentarios];
      #Abre el archivo de comentarios, Si no existe lo crea, si existe lo sobrescribe
      File.open(Ruta_archivos_comentarios, "wb"){
         #Alias
         |f|;
         #Escribe el contenido del archivo.
         f.write(comentarios);
         #Lo cierra para liberar memoria.
         f.close();
      };
   end
   #Verifica si existe el archivo de los comentarios.
   if File.exist?(Ruta_archivos_comentarios)
      #Guarda el contenido del archivo de los comentarios.
      @comentarios = File.read(Ruta_archivos_comentarios);
   else
      #No existe el archivo de los comentarios así que guarda comillas vacías en los comentarios.
      @comentarios = "";
   end
 end
end

app/controllers/formularios_controller.rb
class FormulariosController < ApplicationController
  def post
   @respuesta = false;
   if request.post?
      @comentario = {
         :nombre => params[:nombre],
         :consulta => params[:comentario]
      };
   end
 end
end

app/controllers/redes_sociales_controller.rb
class RedesSocialesController < ApplicationController
   def yo
   end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_url
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/archivos_helper.rb
module ArchivosHelper
end

app/helpers/formularios_helper.rb
module FormulariosHelper
end

app/helpers/redes_sociales_helper.rb
module RedesSocialesHelper
end

app/views/archivos/borrar.html.erb
<h1>Archivos#borrar</h1>
<p>Find me in app/views/archivos/borrar.html.erb</p>

app/views/archivos/guardar.html.erb
<h2> Guardar comentarios </h2>
<%= form_tag({:controller => "archivos", :action => "guardar"}, :method => "post") do %>
   <%= text_area_tag "comentarios", @comentarios, :cols => 50, :rows => 10, :required => "required" %>
   <br />
   <%= submit_tag "Guardar comentario" %>
<% end %>
<p> <%= link_to "Volver a la lista de archivos", :controller => "archivos", :action => "listar" %> </p>

app/views/archivos/listar.html.erb
<h2> Archivos </h2>
<% if @mensaje %>
<!-- Mensaje enviado de la anterior página-->
<div>
   <strong> <%= @mensaje %> </strong>
</div>
<% end %>
<!-- Enlace a la página de subir archivos -->
<p> <%= link_to "Subir archivo", :controller => "archivos", :action => "subir" %> </p>
<!-- Lista de archivos subidos -->
<ul>
   <% @archivos.each do |a| %>
   <% if a == "." or a == ".." then next end; %>
   <li>
      <strong> <%= a %> </strong> | 
      <a target="_blank" href="/archivos/<%= a %>"> Ver archivo </a> | 
      <%= link_to "Borrar archivo", {:controller => "archivos", :action => "borrar", :archivo_a_borrar => a}, {:method => "post", :confirm => "Seguro?"} %>
   </li>
   <% end %>
</ul>
<!-- Acá se guarda el nombre del archivo antes de que el formularo sea enviado-->
<hr />
<!-- Comentarios guardados por el usuario. -->
<h2> Últimos Comentarios: </h2>
<div>
   <pre><%= @comentarios; %></pre>
   <%= link_to "Agregar comentarios", :controller => "archivos", :action => "guardar" %>
</div>

app/views/archivos/subir.html.erb
<h2> Subir archivo </h2>
<%= form_tag({:controller => "archivos", :action => "subir"}, :method => "post", :multipart => true) do %>
   <%= file_field_tag "archivo", :required => "required" %>
   <%= submit_tag "Subir archivo" %>
<% end %>
<% if @formato_erroneo %>
  <div>
     <p> El formato ingresado es incorrecto. Usted sólo puede subir archivos .pdf, .doc y .docx </p>
  </div>
<% end %>
<p> <%= link_to "Volver a la lista de archivos", :controller => "archivos", :action => "listar" %> </p>

app/views/formularios/post.html.erb
<h2> Postea un comentario </h2>
<%= form_tag({:controller => "formularios", :action => "post"}, :method => "post") do %>
   <%= label_tag "nombre", "Nombre" %>
   <br />
   <%= text_field_tag "nombre", "", :required => "required" %>
   <br />
   <%= label_tag "Comentario", "comentario" %>
   <br />
   <%= text_area_tag "comentario", "", :cols => 50, :rows => 10, :required => "required" %>
   <br />
   <%= submit_tag "Enviar comentario" %>
<% end %>
<% if @comentario %>
   <p> <strong><%= @comentario[:nombre] %></strong>, Gracias por publicar tu comentario </p>
   <div class="comentario">
      <%= simple_format (@comentario[:consulta]) %>
   </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Jugando con un Ruby</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="contenedor">
   <header>
      <h1> Jugando con un Ruby | Molinojopiento </h1>
   </header>
   <nav>
      <ul>
         <li class="yo"> <%= link_to "Mi perfil", :controller => "redes_sociales", :action => "yo" %> 
         </li>
         <li class="formulariopost"> <%= link_to "Post", :controller => "formularios", :action => "post" %>
         </li>
          <li class="archivos"> <%= link_to "Subir", :controller => "archivos", :action => "subir" %>
         </li>
      </ul>
      <div class="clear"></div>
   </nav> 
   <section>
   <%= yield %>
   </section> 
   <div id="user-widget">
<div id="user_nav">
  <% if current_user %>
    Signed in as <strong><%= current_user.name %></strong>!
    <%= link_to "Sign out", signout_path, id: "sign_out" %>
  <% else %>
    <%= link_to "Sign in with Facebook", "/auth/facebook", id: "sign_in" %>
  <% end %>
</div>
</div>



</body>
</html>

app/views/layouts/facebook.html.erb
<div class="imagen_logo">
   <%= image_tag "facebook_logo.jpg", :alt => "Facebook", :title => "Facebook"%>
</div>
<div class="descipcion">
   <h2> Facebook </h2>
   <p> Facebook (NASDAQ: FB) es una empresa creada por Mark Zuckerberg y fundada junto a Eduardo Saverin, Chris Hughes y Dustin Moskovitz consistente en un sitio web de redes sociales. Originalmente era un sitio para estudiantes de la Universidad de Harvard, pero actualmente está abierto a cualquier persona que tenga una cuenta de correo electrónico. Los usuarios pueden participar en una o más redes sociales, en relación con su situación académica, su lugar de trabajo o región geográfica. </p>
   <p> Ha recibido mucha atención en la blogosfera y en los medios de comunicación al convertirse en una plataforma sobre la que terceros pueden desarrollar aplicaciones y hacer negocio a partir de la red social. </p>
   <p> A mediados de 2007 lanzó las versiones en francés, alemán y español traducidas por usuarios de manera no remunerada,6 principalmente para impulsar su expansión fuera de Estados Unidos, ya que sus usuarios se concentran en Estados Unidos, Canadá y Reino Unido. Facebook cuenta con más de 900 millones de miembros, y traducciones a 70 idiomas.7 8 En octubre de 2012, Facebook llegó a los 1,000 millones de usuarios, de los cuáles hay más de 600 millones de usuarios móviles. Brasil, India, Indonesia, México y Estados Unidos son los países con el mayor número de usuarios.9 </p>
   <p> Su infraestructura principal está formada por una red de más de 50 000 servidores que usan distribuciones del sistema operativo GNU/Linux usando LAMP.10 </p>
   <p> El 9 de abril de 2012, se anunció que Facebook adquirió Instagram por mil millones de dólares.11 </p>
   <p> Extraído de: <%= link_to "Wikipedia", "http://es.wikipedia.org/wiki/Facebook", :target => "_blank" %> </p>
</div>
<div class="clear"></div>

app/views/redes_sociales/facebook.html.erb
<div class="imagen_logo">
   <%= image_tag "facebook_logo.jpg", :alt => "Facebook", :title => "Facebook"%>
</div>
<div class="descipcion">
   <h2> Facebook </h2>
   <p> Facebook (NASDAQ: FB) es una empresa creada por Mark Zuckerberg y fundada junto a Eduardo Saverin, Chris Hughes y Dustin Moskovitz consistente en un sitio web de redes sociales. Originalmente era un sitio para estudiantes de la Universidad de Harvard, pero actualmente está abierto a cualquier persona que tenga una cuenta de correo electrónico. Los usuarios pueden participar en una o más redes sociales, en relación con su situación académica, su lugar de trabajo o región geográfica. </p>
   <p> Ha recibido mucha atención en la blogosfera y en los medios de comunicación al convertirse en una plataforma sobre la que terceros pueden desarrollar aplicaciones y hacer negocio a partir de la red social. </p>
   <p> A mediados de 2007 lanzó las versiones en francés, alemán y español traducidas por usuarios de manera no remunerada,6 principalmente para impulsar su expansión fuera de Estados Unidos, ya que sus usuarios se concentran en Estados Unidos, Canadá y Reino Unido. Facebook cuenta con más de 900 millones de miembros, y traducciones a 70 idiomas.7 8 En octubre de 2012, Facebook llegó a los 1,000 millones de usuarios, de los cuáles hay más de 600 millones de usuarios móviles. Brasil, India, Indonesia, México y Estados Unidos son los países con el mayor número de usuarios.9 </p>
   <p> Su infraestructura principal está formada por una red de más de 50 000 servidores que usan distribuciones del sistema operativo GNU/Linux usando LAMP.10 </p>
   <p> El 9 de abril de 2012, se anunció que Facebook adquirió Instagram por mil millones de dólares.11 </p>
   <p> Extraído de: <%= link_to "Wikipedia", "http://es.wikipedia.org/wiki/Facebook", :target => "_blank" %> </p>
</div>
<div class="clear"></div>

app/views/redes_sociales/google_mas.html.erb
<div class="imagen_logo">
   <%= image_tag "google_mas_logo.jpg", :alt => "Google +", :title => "Google +"%>
</div>
<div class="descipcion">
   <h2> Google+ </h2>
   <p> Google+ (pronunciado y a veces escrito Google Plus, a veces abreviado como G+, en algunos países de lengua hispana pronunciado Google Más) es un servicio de red social operado por Google Inc. El servicio, lanzado el 28 de junio de 2011, está basado en HTML5. Los usuarios tienen que ser mayores de 18 años de edad,2 para crear sus propias cuentas. Google+ ya es la segunda red social más popular del mundo con aproximadamente 343 millones de usuarios activos. </p>
   <p> Google+ integra los servicios sociales, tales como Google Perfiles y Google Buzz, e introduce los nuevos servicios: Círculos, Quedadas, Intereses y Mensajes.3 Google+ también estará disponible como una aplicación de escritorio y como una aplicación móvil, pero sólo en los sistemas operativos Android e iOS. Fuentes tales como The New York Times lo han declarado el mayor intento de Google para competir con la red social Facebook,4 la cual tenía más de 750 millones de usuarios en 2011.5 El 20 de septiembre de 2011, Google permitió la creación de cuentas a usuarios con más de 18 años, con mejoras en sus extensiones de videoconferencias.6 </p>
   <p> Extraído de: <%= link_to "Wikipedia", "http://es.wikipedia.org/wiki/Google%2B", :target => "_blank" %> </p>
</div>
<div class="clear"></div>

app/views/redes_sociales/twitter.html.erb
<div class="imagen_logo">
   <%= image_tag "twitter_logo.jpg", :alt => "Twitter", :title => "Twitter"%>
</div>
<div class="descipcion">
   <h2> Twitter </h2>
   <p> Twitter es un servicio de microblogging, con sede en San Francisco, California, con filiales en San Antonio Texas y Boston (Massachusetts) en Estados Unidos. Twitter, Inc. fue creado originalmente en California, pero está bajo la jurisdicción de Delaware desde 2007.7 Desde que Jack Dorsey lo creó en marzo de 2006, y lo lanzó en julio del mismo año, la red ha ganado popularidad mundialmente y se estima que tiene más de 200 millones de usuarios, generando 65 millones de tuits al día y maneja más de 800.000 peticiones de búsqueda diarias.1 Ha sido apodado como el "SMS de Internet".8 Entre sus usuarios se destacan grandes figuras públicas, como Barack Obama, actores como Danny DeVito, músicos del estilo de Lady Gaga y Justin Bieber y otros mundialmente conocidos. </p>
   <p> La red permite enviar mensajes de texto plano de corta longitud, con un máximo de 140 caracteres, llamados tuits, que se muestran en la página principal del usuario. Los usuarios pueden suscribirse a los tuits de otros usuarios – a esto se le llama "seguir" y a los usuarios abonados se les llama "seguidores",9 "followers" y a veces tweeps10 ('Twitter' + 'peeps', seguidores novatos que aún no han hecho muchos tweets). Por defecto, los mensajes son públicos, pudiendo difundirse privadamente mostrándolos únicamente a unos seguidores determinados. Los usuarios pueden tuitear desde la web del servicio, con aplicaciones oficiales externas (como para teléfonos inteligentes), o mediante el Servicio de mensajes cortos (SMS) disponible en ciertos países.11 Si bien el servicio es gratis, acceder a él vía SMS comporta soportar tarifas fijadas por el proveedor de telefonía móvil. </p>
   <p> Extraído de: <%= link_to "Wikipedia", "http://es.wikipedia.org/wiki/Twitter", :target => "_blank" %> </p>
</div>
<div class="clear"></div>

app/views/redes_sociales/yo.html.erb
<div class="imagen_logo">
   <%= image_tag "yo.jpg", :alt => "Molino", :title => "Molino", :class =>"img"%>
</div>
<div class="descipcion">
   <h2> Molinojopiento</h2>
   <p> Esto esta sin CSS, fuck! </p>
</div>
<div class="clear"></div>